const ADD_MOVIE = "ADD_MOVIE";
const EDIT_MOVIE = 'EDIT_MOVIE';
const DELETE_MOVIE = "DELETE_MOVIE";
const ADD_COMMENT = 'ADD_COMMENT';
const EDIT_COMMENT = 'EDIT_COMMENT';
const DELETE_COMMENT = 'DELETE_COMMENT';

module.exports = {
    ADD_MOVIE,
    EDIT_MOVIE,
    DELETE_MOVIE,
    ADD_COMMENT,
    EDIT_COMMENT,
    DELETE_COMMENT
}
