version: '3'

services:

  db-mongo:
    restart: always
    image: 'mongo'
    ports:
      - "27017:27017"

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes: 
      - /opt/app/node_modules
      - ./backend:/opt/app
    ports:
      - "4000:4000"

  frontend:
    restart: unless-stopped
    environment: 
      CHOKIDAR_USEPOLLING: "true"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /opt/app/node_modules
      - ./frontend:/opt/app