const UPDATE_SEARCH_KEY = "UPDATE_SEARCH_KEY";
const UPDATE_GENRE_FILTER = "UPDATE_GENRE_FILTER";
const UPDATE_YEAR_SLIDER_RANGE = "UPDATE_YEAR_SLIDER_RANGE";
const UPDATE_YEAR_FILTER = "UPDATE_YEAR_FILTER";
const UPDATE_SORT_KEY = "UPDATE_SORT_KEY";
const UPDATE_SORT_ORDER = "UPDATE_SORT_ORDER";

export const MOVIES_REQUEST = "@@movies/MOVIES_REQUEST";
export const MOVIES_SUCCESS = "@@movies/MOVIES_SUCCESS";
export const MOVIES_FAILURE = "@@movies/MOVIES_FAILURE";

export const ADD_MOVIE_SUCCESS = "@@movies/ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_REQUEST = "@@movies/ADD_MOVIE_REQUEST";
export const ADD_MOVIE_FAILURE = "@@movies/ADD_MOVIE_FAILURE";

export const EDIT_MOVIE_SUCCESS = "@@movies/EDIT_MOVIE_SUCCESS";
export const EDIT_MOVIE_REQUEST = "@@movies/EDIT_MOVIE_REQUEST";
export const EDIT_MOVIE_FAILURE = "@@movies/EDIT_MOVIE_FAILURE";

export const DELETE_MOVIE_REQUEST = "@@movies/DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "@@movies/DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAILURE = "@@movies/DELETE_MOVIE_FAILURE";

export const ADD_COMMENT_SUCCESS = "@@movies/ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_REQUEST = "@@movies/ADD_COMMENT_REQUEST";
export const ADD_COMMENT_FAILURE = "@@movies/ADD_COMMENT_FAILURE";

export const EDIT_COMMENT_SUCCESS = "@@movies/EDIT_COMMENT_SUCCESS";
export const EDIT_COMMENT_REQUEST = "@@movies/EDIT_COMMENT_REQUEST";
export const EDIT_COMMENT_FAILURE = "@@movies/EDIT_COMMENT_FAILURE";

export const DELETE_COMMENT_REQUEST = "@@movies/DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "@@movies/DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "@@movies/DELETE_COMMENT_FAILURE";

const types = {
    UPDATE_SEARCH_KEY,
    UPDATE_GENRE_FILTER,
    UPDATE_YEAR_SLIDER_RANGE,
    UPDATE_YEAR_FILTER,
    UPDATE_SORT_KEY,
    UPDATE_SORT_ORDER,

    MOVIES_REQUEST,
    MOVIES_SUCCESS,
    MOVIES_FAILURE,

    ADD_MOVIE_SUCCESS,
    ADD_MOVIE_REQUEST,
    ADD_MOVIE_FAILURE,

    EDIT_MOVIE_SUCCESS,
    EDIT_MOVIE_REQUEST,
    EDIT_MOVIE_FAILURE,

    DELETE_MOVIE_REQUEST,
    DELETE_MOVIE_SUCCESS,
    DELETE_MOVIE_FAILURE,

    ADD_COMMENT_SUCCESS,
    ADD_COMMENT_REQUEST,
    ADD_COMMENT_FAILURE,

    EDIT_COMMENT_SUCCESS,
    EDIT_COMMENT_REQUEST,
    EDIT_COMMENT_FAILURE,

    DELETE_COMMENT_REQUEST,
    DELETE_COMMENT_SUCCESS,
    DELETE_COMMENT_FAILURE,
};

export default types;
